### ISSUE TITLE
Is this just a GraphQl wrapper over some OpenControl files? 

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/compliance-api#35]
Just curious where the compliance data is coming from

**Comment by maxneuvians** [comment]
Hi @CalvinRodo right now it is parsing a bunch of JSON files that are created by "check" applications. The output of those containers looks something likes this:
```
{
   "origin":"cdssnc/github-reviews-check-compliance:latest",
   "timestamp":"2018-11-23T15:21:29Z",
   "satisfies":[
      "SA-11",
      "SA-11 (4)"
   ],
   "passed":false,
   "description":"The application performs code review on its pull requests.",
   "references":"https://github.com/cds-snc/mrpinchy-confession-box",
   "component":"Infrastructure",
   "release":"43c61288-ef33-11e8-908e-06d86cf01138"
}
```
We looked at the open control schema and it did not really fit the graph structure we were looking to build. 

It looks like you are working in a similar space:

https://github.com/CalvinRodo/GithubComplianceCheck/issues/2

https://github.com/cds-snc/compliance-checks/tree/master/github-reviews-check

It would be great to pick your brain some time on what you are working on and what overlap we could have.

**Comment by CalvinRodo** [comment]
@maxneuvians For sure love to get together and chat. 

My plan with that tool was to create something that just validates a couple of simple checks to prove that a github project is compliant with some basic controls around source code security, I hadn't even thought of using the ITSG-33 controls for it. 

Also I've been meaning to learn go. 

I was planning on setting up ComplianceMasonry for this and documenting using OpenControl but I like your approach better.

**Comment by CalvinRodo** [comment]
Also thanks for the answer :+1:
